workflows:
  default-workflow:
    name: Build InstaClean Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Criar Projeto Flutter
        script: |
          flutter create . --platforms android --org com.instaclean --project-name instaclean
          
      - name: Instalar Dependencias
        script: |
          flutter pub get
          
      - name: Build APK
        script: |
          flutter build apk --debug
          
    artifacts:
      - build/**/outputs/**/*.apk
