workflows:
  default-workflow:
    name: Build InstaClean PMC
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Instalar dependencias
        script: |
          flutter pub get
          
      - name: Build App Bundle (AAB) para Play Store
        script: |
          flutter build appbundle --release --no-tree-shake-icons
          
      - name: Build APK para testes
        script: |
          flutter build apk --release --no-tree-shake-icons
          
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
