# Key properties para assinatura de release
# IMPORTANTE: Não partilhe este ficheiro publicamente!

storePassword=YOUR_STORE_PASSWORD
keyPassword=YOUR_KEY_PASSWORD
keyAlias=instaclean
storeFile=../app/instaclean-release-key.jks
